const S='stikeli_ps_full_v1',R={Common:1,Rare:2,Epic:4,Legendary:8,Mythic:16,Divine:28,Secret:60,Huge:110,Titan:220};
const worldNames=['Meadow Kingdom','Ocean Realm','Sky Realm','Desert Realm','Frozen Realm','Space Realm','Magic Realm','Toy Realm','Cyber Realm','Galaxy Realm'];
const areaNames=['Sunny Meadows','Crystal Forest','Mystic River','Golden Hills','Ancient Ruins','Cloud Valley','Volcano Pass','Dragon Peaks','Moon Temple','Celestial Gate'];
const icons=['🐱','🐰','🦊','🐶','🐧','🐉','🐺','🐯','🦈','🦄','🦅','🗿','🦦','🦎','🦝','🐻'];
const pets=Array.from({length:500},(_,i)=>{let r=i%50;let rar=r%10===0?'Secret':r>=8?'Legendary':r>=6?'Epic':r>=4?'Rare':'Common';return{id:i+1,n:i?'Crystal '+icons[i%icons.length]:'Starter Cat',rar,p:Math.floor(5*Math.pow(2.4,Math.floor(i/20))*(1+(i%17)/20)),icon:icons[i%icons.length]}});
const areas=Array.from({length:50},(_,i)=>({id:i+1,w:Math.floor(i/5)+1,name:(i<10?areaNames[i]:`${worldNames[Math.floor(i/5)]} • Zone ${i%5+1}`),cost:i?Math.floor(900*Math.pow(7.2,i-1)):0}));
const eggs=Array.from({length:100},(_,i)=>({id:i+1,area:(i%50)+1,cost:Math.floor(100*Math.pow(3.1,i%10)*Math.pow(8,Math.floor(i/10))),pool:Array.from({length:5},(_,k)=>Math.min(500,1+i*5+k))}));
const Q=[['First Steps','break',10,250,0],['Egg Explorer','egg',5,1000,50],['Growing Strong','power',5000,0,200],['World Walker','area',5,25000,500],['Pet Collector','collect',20,0,1500]];
let d=load();let page='play';
function base(){return{coins:500,gems:100,tokens:0,area:1,open:[1],pets:[{u:uid(),id:1,v:'Normal',lv:1,lock:false}],eq:[],up:{coin:0,gem:0,dmg:0,luck:0,slots:0,hatch:0,store:0,magnet:0},stats:{break:0,egg:0,trade:0,coin:0,gem:0,play:0},q:{},ach:{},collection:{1:1}}}
function load(){try{return Object.assign(base(),JSON.parse(localStorage.getItem(S)||'{}'))}catch{return base()}}
function uid(){return crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now()}
function save(silent){localStorage.setItem(S,JSON.stringify(d));if(!silent)toast('Spielstand gespeichert 💾')}
function fmt(x){return Intl.NumberFormat('de-DE',{notation:'compact',maximumFractionDigits:1}).format(x)}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.getElementById('pop').append(x);setTimeout(()=>x.remove(),2200)}
function cfg(p){return pets.find(x=>x.id===p.id)||pets[0]}
function vm(v){return v==='Golden'?1.5:v==='Rainbow'?2.3:v==='Huge'?3.3:v==='Titan'?5:1}
function power(){return d.eq.reduce((s,u)=>{let p=d.pets.find(x=>x.u===u);return s+cfg(p).p*(p.lv||1)*vm(p.v)},0)}
function slots(){return 4+d.up.slots}
function nav(){let a=[['play','🏠','Play'],['pets','🐾','Pets'],['eggs','🥚','Eggs'],['worlds','🌎','Worlds'],['quests','📜','Quests'],['up','⚡','Upgrades'],['market','🛒','Market'],['trade','🤝','Trading'],['ach','🏆','Achievements'],['profile','👤','Profile'],['admin','🛠️','Admin']];document.getElementById('nav').innerHTML=a.map(x=>`<button class="nav ${page===x[0]?'on':''}" data-page="${x[0]}">${x[1]} <span>${x[2]}</span></button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function render(){nav();document.getElementById('coins').textContent=fmt(d.coins);document.getElementById('gems').textContent=fmt(d.gems);document.getElementById('tokens').textContent=fmt(d.tokens);let h=page==='play'?play():page==='pets'?petsUI():page==='eggs'?eggsUI():page==='worlds'?worldsUI():page==='quests'?questsUI():page==='up'?upUI():page==='market'?marketUI():page==='trade'?tradeUI():page==='ach'?achUI():page==='profile'?profileUI():adminUI();document.getElementById('app').innerHTML=`<div class="main">${h}</div>`;bind()}
function play(){let a=areas[d.area-1];return`<div class="hero"><div class="card"><div class="tag">WORLD ${a.w} • AREA ${a.id}</div><h1>${a.name}</h1><p class="muted">Sammle Coins, öffne Eggs, verbessere dein Team und schalte immer neue Zonen frei.</p><div class="row" style="margin-top:18px"><button class="btn primary" id="break">💥 Breakable</button><button class="btn" id="best">⚡ Equip Best</button><button class="btn" id="eggo">🥚 Eggs</button></div></div><div class="card"><div class="row"><b>Your Team</b><span class="tag">${d.eq.length}/${slots()}</span></div><div style="font-size:32px;font-weight:900;margin-top:12px">${fmt(power())}</div><div class="muted">Total Pet Power</div><div class="stack" style="margin-top:12px">${d.eq.slice(0,4).map(u=>{let p=d.pets.find(x=>x.u===u);return`<span class="tag">${cfg(p).icon} ${cfg(p).n}</span>`}).join('')||'<div class="muted">Equip ein Pet, um loszulegen.</div>'}</div></div></div><div class="head"><h2>Breakables</h2><span class="muted">Pet Power: ${fmt(power())}</span></div><div class="grid c2">${Array.from({length:6},(_,i)=>`<div class="card"><div class="row"><span style="font-size:30px">${['📦','💎','🎁','🪨','🔮','🧰'][i]}</span><div style="flex:1"><b>${['Wooden Chest','Crystal Pile','Gift Crate','Mystic Rock','Rune Core','Treasure Box'][i]}</b><div class="muted">${fmt(100*Math.pow(2.4,d.area-1)*(1+i*.2))} HP</div><div class="bar"><i style="width:${Math.max(10,100-(d.stats.break+i)%9*9)}%"></i></div></div><button class="btn" data-b="1">⚔️</button></div></div>`).join('')}</div>`}
function petCard(p){let c=cfg(p);return`<div class="card pet"><div class="art">${c.icon}</div><span class="tag">${c.rar}${p.v!=='Normal'?' • '+p.v:''}</span><b>${c.n}</b><div class="muted">${fmt(c.p*p.lv*vm(p.v))} Power • Lv.${p.lv}</div><div class="row" style="margin-top:10px"><button class="btn" data-e="${p.u}">${d.eq.includes(p.u)?'Unequip':'Equip'}</button><button class="btn" data-d="${p.u}">Details</button></div></div>`}
function petsUI(){return`<div class="head"><div><h2>Pet Inventory</h2><div class="muted">${d.pets.length}/500 • ${d.eq.length}/${slots()} equipped</div></div><div class="row"><button class="btn" id="best">⚡ Equip Best</button><button class="btn" id="fuse">🔮 Fuse 5</button></div></div><div class="grid c4">${d.pets.map(petCard).join('')}</div>`}
function eggsUI(){return`<div class="head"><div><h2>Eggs</h2><div class="muted">100 Eggs across 50 Areas</div></div><button class="btn primary" id="auto">🔁 Auto Hatch ×10</button></div><div class="grid c3">${eggs.filter(e=>d.open.includes(e.area)||e.area<=Math.max(...d.open)+2).slice(0,30).map(e=>{let ok=d.open.includes(e.area);return`<div class="card"><div class="art">🥚</div><b>Egg #${e.id}</b><div class="muted">Area ${e.area} • ${fmt(e.cost)} Coins</div><div class="tag">${e.pool.map(id=>pets[id-1].icon).join(' ')}</div><button class="btn primary" data-h="${e.id}" style="margin-top:10px" ${ok?'':'disabled'}>${ok?'Open Egg':'Locked'}</button></div>`}).join('')}</div>`}
function worldsUI(){return`<h2>Worlds & Areas</h2><div class="grid c3">${worldNames.map((w,wi)=>`<div class="card"><span class="tag">WORLD ${wi+1}</span><h3>${w}</h3><div class="stack">${areas.slice(wi*5,wi*5+5).map(a=>{let ok=d.open.includes(a.id);return`<div class="row"><span>${a.name}<br><small class="muted">${a.cost?fmt(a.cost)+' Coins':'FREE'}</small></span><button class="btn" data-a="${a.id}">${ok?'Enter':'Unlock'}</button></div>`}).join('')}</div></div>`).join('')}</div>`}
function qval(q){let t=q[1],g=q[2];return t==='break'?Math.min(g,d.stats.break):t==='egg'?Math.min(g,d.stats.egg):t==='power'?Math.min(g,power()):t==='area'?Math.min(g,Math.max(...d.open)):Math.min(g,Object.keys(d.collection).length)}
function questsUI(){return`<h2>Quests</h2><div class="stack">${Q.map((q,i)=>{let v=qval(q),ok=v>=q[2],cl=d.q[i];return`<div class="card row"><div style="flex:1"><b>${q[0]}</b><div class="muted">${fmt(v)} / ${fmt(q[2])}</div><div class="bar"><i style="width:${Math.min(100,v/q[2]*100)}%"></i></div></div><span class="tag">🪙 ${fmt(q[3])} ${q[4]?`• 💎 ${fmt(q[4])}`:''}</span><button class="btn ${ok&&!cl?'primary':''}" data-q="${i}" ${!ok||cl?'disabled':''}>${cl?'Claimed':ok?'Claim':'Progress'}</button></div>`}).join('')}</div>`}
function upUI(){let ups=[['coin','Coin Multiplier'],['gem','Diamond Multiplier'],['dmg','Pet Damage'],['luck','Egg Luck'],['slots','Pet Slots'],['hatch','Hatch Speed'],['store','Storage'],['magnet','Magnet Range']];return`<h2>Upgrade Lab</h2><div class="grid c4">${ups.map(u=>{let l=d.up[u[0]]||0,c=Math.floor(50*Math.pow(2.1,l));return`<div class="card"><span class="tag">⚡ ${u[1]}</span><div style="font-size:28px;font-weight:900">Lv.${l}</div><div class="muted">Cost 💎 ${fmt(c)}</div><button class="btn primary" data-u="${u[0]}">Upgrade</button></div>`}).join('')}</div>`}
function marketUI(){let ls=Array.from({length:12},(_,i)=>pets[(i*41+7)%500]);return`<h2>Trading Plaza Market</h2><div class="muted" style="margin-bottom:14px">Lokaler Markt für die statische GitHub-Pages-Version.</div><div class="stack">${ls.map((c,i)=>{let price=Math.floor(c.p*R[c.rar]*(1.4+i*.15));return`<div class="card row"><span style="font-size:30px">${c.icon}</span><div style="flex:1"><b>${c.n}</b><div class="muted">${c.rar} • ${fmt(c.p)} Power • Seller ${['Luna','Mika','Nova','Pixel','Kori'][i%5]}</div></div><span class="tag">💎 ${fmt(price)}</span><button class="btn" data-buy="${i}">Buy</button></div>`}).join('')}</div>`}
function tradeUI(){return`<div class="grid c2"><div class="card"><h2>Trading</h2><p class="muted">Für echtes Cross-User-Trading braucht Stikeli-PS später ein Backend. Diese Version enthält den kompletten UI-/Inventarfluss als lokale Spielsimulation.</p><div class="stack">${['Luna','Mika','Nova','Pixel','Kori','Zed'].map(x=>`<div class="row"><span>🧑 ${x}</span><button class="btn" data-t="${x}">Trade Request</button></div>`).join('')}</div></div><div class="card"><h2>Safety</h2><div class="stack"><span class="tag">🔒 Locked Pets werden geschützt</span><span class="tag">⭐ Favorites können erweitert werden</span><span class="tag">🆔 Jede Instanz besitzt eine UID</span><span class="tag">✅ Trades ändern deinen lokalen Spielstand</span></div></div></div>`}
function achUI(){let n=Object.keys(d.ach).length;return`<div class="head"><div><h2>Achievements</h2><div class="muted">${n}/100</div></div></div><div class="stack">${Array.from({length:100},(_,i)=>{let goal=[1,5,100,1000,1000000][i%5],ok=i%5===0?d.pets.length>=goal:i%5===1?d.stats.egg>=goal:i%5===2?d.stats.break>=goal:i%5===3?d.stats.break>=goal:d.stats.coin>=goal;return`<div class="card row"><span>${ok?'🏆':'🔒'} Achievement ${i+1}</span><small class="muted">Goal ${fmt(goal)}</small><button class="btn ${ok&&!d.ach[i]?'primary':''}" data-ach="${i}" ${!ok||d.ach[i]?'disabled':''}>${d.ach[i]?'Done':ok?'Claim':'Locked'}</button></div>`}).join('')}</div>`}
function profileUI(){let best=[...d.pets].sort((a,b)=>cfg(b).p*vm(b.v)-cfg(a).p*vm(a.v))[0];return`<div class="grid c3"><div class="card"><span class="tag">PROFILE</span><h2>Stikeli Player</h2><div class="muted">Local Web Account</div><div class="row" style="margin-top:16px"><span>Rank</span><b>${rank()}</b></div><div class="row"><span>Collection</span><b>${Object.keys(d.collection).length}/500</b></div></div><div class="card"><div class="muted">Best Pet</div><h2>${best?cfg(best).icon+' '+cfg(best).n:'-'}</h2><div style="font-size:30px;font-weight:900">${best?fmt(cfg(best).p*best.lv*vm(best.v)):0}</div></div><div class="card"><div class="stack"><div class="row"><span>Coins Earned</span><b>${fmt(d.stats.coin)}</b></div><div class="row"><span>Eggs Opened</span><b>${fmt(d.stats.egg)}</b></div><div class="row"><span>Breakables</span><b>${fmt(d.stats.break)}</b></div><div class="row"><span>Trades</span><b>${fmt(d.stats.trade)}</b></div></div></div></div>`}
function rank(){let s=d.stats.coin+power()*10;return['Beginner','Explorer','Adventurer','Champion','Master','Legend','Royal','Mythic','Celestial','Cosmic'][Math.min(9,Math.max(0,Math.floor(Math.log10(Math.max(1,s)))))]}
function adminUI(){return`<div class="grid c2"><div class="card"><h2>Admin Console</h2><p class="muted">Lokaler Entwicklerbereich. Der Code ist nicht als sichere Server-Authentifizierung gedacht.</p><input id="code" placeholder="Admin Code" style="width:100%;padding:10px;border-radius:10px;border:1px solid var(--l);background:#0b1221;color:var(--t)"><button class="btn primary" id="unlock" style="margin-top:10px">Unlock</button><div id="tools"></div></div><div class="card"><h2>Diagnostics</h2><div class="stack"><div class="row"><span>Pets</span><b>${d.pets.length}</b></div><div class="row"><span>Areas</span><b>${d.open.length}/50</b></div><div class="row"><span>Collection</span><b>${Object.keys(d.collection).length}/500</b></div><div class="row"><span>Build</span><b>Stikeli-PS Web Full</b></div></div></div></div>`}
function bind(){document.getElementById('break')?.addEventListener('click',()=>breakIt());document.querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>breakIt());document.getElementById('best')?.addEventListener('click',equipBest);document.getElementById('eggo')?.addEventListener('click',()=>{page='eggs';render()});document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>toggle(b.dataset.e));document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>detail(b.dataset.d));document.getElementById('fuse')?.addEventListener('click',fuse);document.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>hatch(+b.dataset.h));document.getElementById('auto')?.addEventListener('click',()=>{let i=0;while(i<10){let e=eggs.find(e=>d.open.includes(e.area)&&d.coins>=e.cost);if(!e)break;hatch(e.id,true);i++}toast(`Auto Hatch: ${i}`);render()});document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>areaGo(+b.dataset.a));document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>claimQ(+b.dataset.q));document.querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>upg(b.dataset.u));document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(+b.dataset.buy));document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>trade(b.dataset.t));document.querySelectorAll('[data-ach]').forEach(b=>b.onclick=()=>claimA(+b.dataset.ach));document.getElementById('unlock')?.addEventListener('click',adm);}
function breakIt(){let v=Math.floor((100+power()*1.1)*(1+d.up.coin*.15));d.coins+=v;d.stats.coin+=v;d.stats.break++;if(Math.random()<.08){d.gems+=2+d.up.gem;d.stats.gem+=2+d.up.gem}toast(`+${fmt(v)} Coins 🪙`);save(1);render()}
function equipBest(){d.eq=d.pets.slice().sort((a,b)=>cfg(b).p-cfg(a).p).slice(0,slots()).map(x=>x.u);toast('Best Pets equipped');save(1);render()}
function toggle(u){let i=d.eq.indexOf(u);if(i>=0)d.eq.splice(i,1);else{if(d.eq.length>=slots())return toast(`Max ${slots()} Slots`);d.eq.push(u)}save(1);render()}
function detail(u){let p=d.pets.find(x=>x.u===u),c=cfg(p);openModal(c.n,`<div class="art">${c.icon}</div><div class="stack"><div class="row"><span>Rarity</span><b>${c.rar}</b></div><div class="row"><span>Variant</span><b>${p.v}</b></div><div class="row"><span>Level</span><b>${p.lv}</b></div><div class="row"><span>Power</span><b>${fmt(c.p*p.lv*vm(p.v))}</b></div><div class="row"><span>UID</span><small>${p.u}</small></div></div>`)}
function hatch(id,quiet){let e=eggs.find(x=>x.id===id);if(!e||!d.open.includes(e.area))return;if(d.coins<e.cost)return toast('Nicht genug Coins');d.coins-=e.cost;let id2=e.pool[(Math.random()*e.pool.length)|0];let c=pets[id2-1],v='Normal',r=Math.random();if(r<.003)v='Titan';else if(r<.009)v='Rainbow';else if(r<.03)v='Golden';else if(c.rar==='Secret'&&r<.12)v='Huge';let p={u:uid(),id:c.id,v,lv:1,lock:false};d.pets.push(p);d.collection[c.id]=1;d.stats.egg++;if(!quiet)toast(`${v==='Normal'?'🥚':'✨'} ${v} ${c.n}`);save(1)}
function areaGo(id){let a=areas[id-1];if(d.open.includes(id)){d.area=id;toast(`${a.name} betreten`);render();return}if(d.coins<a.cost)return toast(`Benötigt ${fmt(a.cost)} Coins`);d.coins-=a.cost;d.open.push(id);d.area=id;toast(`${a.name} freigeschaltet 🎉`);save(1);render()}
function claimQ(i){let q=Q[i];if(qval(q)<q[2]||d.q[i])return;d.q[i]=1;d.coins+=q[3];d.gems+=q[4];toast(`Quest: ${q[0]} abgeschlossen`);save(1);render()}
function upg(k){let l=d.up[k]||0,c=Math.floor(50*Math.pow(2.1,l));if(d.gems<c)return toast('Nicht genug Diamonds');d.gems-=c;d.up[k]=l+1;toast(`${k} Lv.${l+1}`);save(1);render()}
function buy(i){let c=pets[(i*41+7)%500],price=Math.floor(c.p*R[c.rar]*(1.4+i*.15));if(d.gems<price)return toast('Nicht genug Diamonds');d.gems-=price;d.pets.push({u:uid(),id:c.id,v:'Normal',lv:1,lock:false});d.collection[c.id]=1;d.stats.trade++;toast(`${c.n} gekauft`);save(1);render()}
function trade(name){let c=pets[(Math.random()*pets.length)|0];d.pets.push({u:uid(),id:c.id,v:'Normal',lv:1,lock:false});d.stats.trade++;toast(`Trade mit ${name}: ${c.n} erhalten`);save(1);render()}
function fuse(){let g={};d.pets.filter(p=>!p.lock).forEach(p=>(g[p.id]??=[]).push(p));let x=Object.values(g).find(a=>a.length>=5);if(!x)return toast('Du brauchst 5 gleiche freie Pets');x.slice(0,5).forEach(p=>d.pets=d.pets.filter(y=>y.u!==p.u));d.pets.push({u:uid(),id:x[0].id,v:'Golden',lv:1,lock:false});toast('Fusion erfolgreich ✨');save(1);render()}
function claimA(i){let goal=[1,5,100,1000,1000000][i%5],ok=i%5===0?d.pets.length>=goal:i%5===1?d.stats.egg>=goal:i%5===2?d.stats.break>=goal:i%5===3?d.stats.break>=goal:d.stats.coin>=goal;if(!ok||d.ach[i])return;d.ach[i]=1;d.gems+=100;toast('Achievement abgeschlossen 🏆');save(1);render()}
function openModal(t,b){let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="box"><div class="row"><h2>${t}</h2><button class="btn" id="mx">✕</button></div><div style="margin-top:12px">${b}</div></div>`;document.body.append(m);m.onclick=e=>{if(e.target===m)m.remove()};m.querySelector('#mx').onclick=()=>m.remove()}
document.getElementById('save').onclick=()=>save();document.getElementById('settings').onclick=()=>openModal('Settings',`<div class="stack"><div class="row"><span>Auto Save</span><b>ON</b></div><div class="row"><span>Responsive UI</span><b>ON</b></div><div class="row"><span>Local Save</span><b>ON</b></div></div>`);
function adm(){if(document.getElementById('code').value!=='STIKELI-ADMIN-2026')return toast('Falscher Code');document.getElementById('tools').innerHTML='<div class="head"><h3>Admin Tools</h3></div><div class="row"><button class="btn" id="gc">+1M Coins</button><button class="btn" id="gg">+100K Diamonds</button><button class="btn" id="gh">Spawn Huge</button><button class="btn" id="ua">Unlock All</button></div>';document.getElementById('gc').onclick=()=>{d.coins+=1e6;save();render()};document.getElementById('gg').onclick=()=>{d.gems+=1e5;save();render()};document.getElementById('gh').onclick=()=>{d.pets.push({u:uid(),id:351,v:'Huge',lv:1,lock:false});save();toast('Huge Pet erstellt');render()};document.getElementById('ua').onclick=()=>{d.open=areas.map(a=>a.id);save();toast('Alle Areas offen');render()}}
setInterval(()=>{d.stats.play+=1;localStorage.setItem(S,JSON.stringify(d))},30000);render();