const API='https://ps99.biggamesapi.io';
const ADMIN_CODE='Stikeli';
const state={pets:[],search:'',category:'all',variant:'all',sort:'rapDesc',limit:60};
const favs=new Set(JSON.parse(localStorage.getItem('stikeli-favs')||'[]'));
const custom=JSON.parse(localStorage.getItem('stikeli-custom')||'{}');
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>{n=Number(n||0);if(!n)return'—';for(const [v,s] of [[1e15,'Q'],[1e12,'T'],[1e9,'B'],[1e6,'M'],[1e3,'K']])if(n>=v)return(n/v).toLocaleString('de-DE',{maximumFractionDigits:2})+s;return n.toLocaleString('de-DE')};
const idOf=p=>p.id||p.configData?.id||p.configName||'Unknown Pet';
const variant=p=>p.variant==='gold'?'Golden':p.variant==='rainbow'?'Rainbow':p.shiny?'Shiny':'Normal';
const key=p=>`${idOf(p)}|${p.variant||'normal'}|${p.shiny?'1':'0'}`;
function iconUrl(p){let x=p.icon||p.thumbnail||p.configData?.thumbnail||p.configData?.goldenThumbnail||'';if(!x)return'';x=String(x);if(x.startsWith('http'))return x;const m=x.match(/(\d{6,})/);return m?`https://www.roblox.com/asset-thumbnail/image?assetId=${m[1]}&width=420&height=420&format=png`:''}
async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function normalizePet(p,rapMap,existsMap){const id=idOf(p);const k=String(id).toLowerCase();let r=Number(p.rap||p.value||0),e=Number(p.exists||0);const rr=rapMap.get(k);const ee=existsMap.get(k);if(rr!=null)r=rr;if(ee!=null)e=ee;const c=custom[key(p)]||{};return{...p,id,rap:Number(c.rap??r),exists:Number(c.exists??e),icon:iconUrl(p)}}
function maps(rows){const r=new Map(),e=new Map();for(const x of rows||[]){const d=x.configData||x.config||x;const id=String(d.id||d.name||x.id||'').toLowerCase();const v=Number(x.value??x.rap??0);if(id&&v)r.set(id,v);const ex=Number(x.value??x.exists??0);if(id&&ex)e.set(id,ex)}return[r,e]}
async function load(){try{$('live').innerHTML='<i></i> LADEN…';const [pets,rap,exists]=await Promise.all([get('/api/collection/Pets'),get('/api/rap'),get('/api/exists')]);const bases=pets.data||[];const [rm,em]=maps(rap.data||[]);const [_,existsMap]=maps(exists.data||[]);state.pets=bases.map(p=>normalizePet(p,rm,existsMap));$('loading').classList.add('hidden');$('live').innerHTML='<i></i> LIVE';updateStats();render()}catch(err){console.error(err);$('loading').innerHTML='<b>Die Pet-Daten konnten nicht geladen werden.</b><span>Bitte später erneut auf ↻ Aktualisieren klicken.</span>';toast('API konnte nicht geladen werden')}}
function filtered(){let a=state.pets.filter(p=>{const q=state.search.toLowerCase();if(q&&!`${p.id} ${p.category||''} ${variant(p)}`.toLowerCase().includes(q))return false;if(state.category!=='all'&&(p.category||'Normal')!==state.category)return false;if(state.variant!=='all'&&(state.variant==='shiny'?!p.shiny:p.variant!==state.variant))return false;return true});return a.sort((x,y)=>{if(state.sort==='rapAsc')return x.rap-y.rap;if(state.sort==='existsAsc')return x.exists-y.exists;if(state.sort==='existsDesc')return y.exists-x.exists;if(state.sort==='name')return x.id.localeCompare(y.id);return y.rap-x.rap})}
function card(p){const k=key(p);return `<article class="pet-card"><button class="fav ${favs.has(k)?'active':''}" data-fav="${esc(k)}">★</button><div class="pet-image">${p.icon?`<img src="${esc(p.icon)}" alt="${esc(p.id)}" loading="lazy" onerror="this.style.display='none';this.parentElement.classList.add('no-image')">`:'<span style="font-size:50px">🐾</span>'}</div><div class="pet-name" title="${esc(p.id)}">${esc(p.id)}</div><div class="tag-row"><span class="tag">${esc(p.category||'Pet')}</span><span class="tag">${variant(p)}</span></div><div class="value-row"><div class="value"><small>RAP</small><b>${fmt(p.rap)} 💎</b></div><div class="value"><small>EXISTS</small><b>${fmt(p.exists)}</b></div></div><button class="details" data-open="${esc(k)}">Details ansehen</button></article>`}
function render(){const all=filtered(),shown=all.slice(0,state.limit);$('grid').innerHTML=shown.map(card).join('');$('found').textContent=all.length.toLocaleString('de-DE');$('total').textContent=state.pets.length.toLocaleString('de-DE');$('quickTotal').textContent=state.pets.length.toLocaleString('de-DE');$('rapTotal').textContent=state.pets.filter(p=>p.rap).length.toLocaleString('de-DE');$('rareTotal').textContent=state.pets.filter(p=>['Huge','Titanic'].includes(p.category)).length.toLocaleString('de-DE');$('more').classList.toggle('hidden',shown.length>=all.length);$('empty').classList.toggle('hidden',all.length>0);bindCards()}
function updateStats(){const a=state.pets.filter(p=>p.rap).sort((x,y)=>y.rap-x.rap);$('highest').textContent=a[0]?`${a[0].id} · ${fmt(a[0].rap)}`:'—'}
function bindCards(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();const k=b.dataset.fav;favs.has(k)?favs.delete(k):favs.add(k);localStorage.setItem('stikeli-favs',JSON.stringify([...favs]));render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open))}
function openDetail(k){const p=state.pets.find(x=>key(x)===k);if(!p)return;const c=custom[k]||{};$('drawer').classList.add('open');$('detail').innerHTML=`<div class="detail"><div class="detail-image">${p.icon?`<img src="${esc(p.icon)}" alt="${esc(p.id)}">`:'🐾'}</div><h2>${esc(p.id)}</h2><div class="detail-sub">${esc(p.category||'Pet')} · ${variant(p)}</div><div class="detail-grid"><div class="detail-box"><small>RAP</small><b>${fmt(p.rap)} 💎</b></div><div class="detail-box"><small>EXISTS</small><b>${fmt(p.exists)}</b></div><div class="detail-box"><small>MAX PAY</small><b>${fmt(Math.round(p.rap*Number(c.maxMultiplier??localStorage.getItem('stikeli-max-multiplier')??.95)))} 💎</b></div><div class="detail-box"><small>FAVORIT</small><b>${favs.has(k)?'⭐ Ja':'Nein'}</b></div></div></div>`}
function openAdmin(){if(!sessionStorage.getItem('stikeli-admin')){$('adminBody').innerHTML='<h2>🛠 Stikeli Admin</h2><p>Admin-Code eingeben.</p><div class="admin-field"><label>Code</label><input id="adminCode" type="password" placeholder="Code"></div><button class="primary" id="login">Einloggen</button>';$('login').onclick=()=>{if($('adminCode').value===ADMIN_CODE){sessionStorage.setItem('stikeli-admin','1');openAdmin()}else toast('Falscher Code')};return}const mult=localStorage.getItem('stikeli-max-multiplier')||'.95';$('adminBody').innerHTML=`<h2>🛠 Stikeli Admin</h2><p class="detail-sub">Lokale Einstellungen für diese Website.</p><div class="admin-field"><label>Standard Max-Pay Multiplikator</label><input id="mult" type="number" step=".01" min="0" max="2" value="${mult}"></div><button class="primary" id="save">Speichern</button><button class="secondary" id="logout" style="margin-left:8px">Logout</button>`;$('save').onclick=()=>{localStorage.setItem('stikeli-max-multiplier',$('mult').value);toast('Gespeichert')};$('logout').onclick=()=>{sessionStorage.removeItem('stikeli-admin');openAdmin()}}
$('search').oninput=e=>{state.search=e.target.value;state.limit=60;render()};$('category').onchange=e=>{state.category=e.target.value;state.limit=60;render()};$('variant').onchange=e=>{state.variant=e.target.value;state.limit=60;render()};$('sort').onchange=e=>{state.sort=e.target.value;render()};$('more').onclick=()=>{state.limit+=60;render()};$('refresh').onclick=load;$('random').onclick=()=>{const a=state.pets.filter(p=>p.rap);if(a.length)openDetail(key(a[Math.floor(Math.random()*a.length)]))};$('theme').onclick=()=>{document.body.classList.toggle('light');toast('Theme geändert')};$('adminOpen').onclick=()=>{$('admin').classList.add('open');openAdmin()};$('adminClose').onclick=()=>$('admin').classList.remove('open');document.querySelector('.modal-bg').onclick=()=>$('admin').classList.remove('open');$('close').onclick=()=>$('drawer').classList.remove('open');document.querySelector('.drawer-bg').onclick=()=>$('drawer').classList.remove('open');document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('search').focus()}if(e.key==='Escape')document.querySelectorAll('.open').forEach(x=>x.classList.remove('open'))});
load();